/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Main coursebook sidebar
  coursebookSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Chapter 1: Foundations of Physical AI',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapter-01',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: Perception Systems',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapter-02',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Motion Planning & Control',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapter-03',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Learning & Adaptation',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapter-04',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 5: System Integration',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapter-05',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 6: Applications',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapter-06',
        },
      ],
    },
  ],
};

export default sidebars;
